apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ck62vmkuh-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ad83387ae2.b5uv.p3.openshiftapps.com/rhtap/rhtap-qe:5e65d093d92cee6739e56abbbfbab77b630003f5@sha256:5611195c71b2d8f6abea476be4c35ad354006ff14bb381d3928a9aa07b087258
          name: container-image
